-- MySQL Script generated by MySQL Workbench
-- Wed Nov  4 22:38:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_um_problema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_um_problema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_um_problema` DEFAULT CHARACTER SET utf8 ;
USE `db_um_problema` ;

-- -----------------------------------------------------
-- Table `db_um_problema`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_um_problema`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cpf` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `Tipo` ENUM('adm', 'gestor', 'usuario') NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_um_problema`.`demandas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_um_problema`.`demandas` (
  `iddemandas` INT NOT NULL AUTO_INCREMENT,
  `categorias` VARCHAR(45) NULL,
  `local` VARCHAR(80) NULL,
  `resumo` VARCHAR(80) NULL,
  `requerente` INT NULL,
  `status` ENUM('resolvido', 'analise', 'recebida', 'negado') NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`iddemandas`, `usuario_idusuario`),
  INDEX `fk_demandas_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_demandas_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `db_um_problema`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
